name: 'Firefox Addon Action'
description: 'Github action to upload firefox addon.'
author: 'yayuyokitano'
inputs:
  guid:
    required: true
    description: 'uuid of extension to update'
  xpi_path:
    required: true
    description: 'path to XPI file'
  api_key:
    required: true
    description: 'API key for AMO'
  api_secret:
    required: true
    description: 'API secret for AMO'
  src_path:
    description: 'path to src zip file for verification. To be used if your extension uses minification, or other build steps that make it difficult to read the code of the xpi.'
runs:
  using: 'node16'
  main: 'dist/index.js'
